### PR TITLE
Improve Contribution guide by introducing "complete" profile & clarifying java version

### PR DESCRIPTION
**Pull request by nicornk**
# Summary
While trying to run the unit tests on a new computer/within Codespaces I realized that the contribution guide could be improved. With these changes it should be straight forward to follow to get Green Unit Tests on the first try.

# Checklist

- [X] You agree with our [CLA](https://gist.githubusercontent.com/emdgroup-admin/16cc45ea4315c2ef29eb9d9afc36fcf5/raw/abb9c91f15278a62b9ac3e66144bcd27fa9485c2/CLA.md)
- [ ] Included tests (or is not applicable).
- [X] Updated [documentation](https://emdgroup.github.io/foundry-dev-tools/) (or is not applicable).
- [X] Used [pre-commit hooks](https://emdgroup.github.io/foundry-dev-tools/develop.html#pre-commit-hooks-formatting) to format and lint the code.

### CODE REVIEW

**Comment by jonas-w** [comment]
Maybe we should also add this to docs/installation.md and include a way to do this with mamba/conda via `mamba install 'openjdk==17.*' pyspark`? Or we could create a seperate documentation were we include all the information about pyspark, so we can link from docs/installation.md and docs/develop.md?

**Comment by jonas-w** [comment]
The "complete" profile is a good idea, but what do you think about if we do an "all" extra, that contains transforms, cli and s3. Whiche end-users could use. And then a "dev" extra, which contains "all" + testing and integration + maybe pre-commit for contributors?

**Comment by nicornk** [comment]
Good points. I feel like we overcomplicate a little bit. 
What if we include the dependencies of "s3" and "cli" in the default dependencies and than have "all" (default + transforms) and dev (all, integration, testing, pre-commit, tox)?

I think a seperate documentation about the pyspark and Java quirks make sense.

**Comment by jonas-w** [comment]
> Good points. I feel like we overcomplicate a little bit. What if we include the dependencies of "s3" and "cli" in the default dependencies and than have "all" (default + transforms) and dev (all, integration, testing, pre-commit, tox)?
> 
> I think a seperate documentation about the pyspark and Java quirks make sense.

I think we should leave the extras as is for now, and think about it again in the v2, where we already thought about splitting the extras into packages. Though I wouldn't mind the extra "extras" 'all' and 'dev'.

I've tested a bit, and with `pip install -e '.'`, `pip freeze` shows 21 packages, but with `pip install -e '.[s3,cli]'`, it would be 48 packages, more than 2x amount of dependencies.

Making s3 the default, may be interesting when we start using the s3 compatible dataset API for other things.

We would also need to patch this again in the lambda layers, if we start depending on these packages per default 😅

**Comment by jonas-w** [comment]
Obsolete as package management changed, so contribution guide also changed.

**Pull request closed without merging**
