### PR TITLE
Initial PR for a new structure of exceptions.

### LINKED ISSUE #5: Export foundry-dev-tool errors such as DatasetHasOpenTransactionError
### Issue checklist

- [X] This is a **feature request**/**enhancement**. And not a bug.
- [X] I searched through the GitHub issues and this feature/enhancement has not been requested before.
- [x] I have installed the latest version of Foundry DevTools and don't use an unsupported python version.
- [X] Others could also benefit from this feature or enhancement and it is **not** a very specific use case.

### Feature use case

The export of Error types would make it possible to catch raised errors and handle them accordingly.

### Description of the Feature

An import of the errors like
```
from foundry_dev_tools import DatasetHasOpenTransactionError

try:
   # something
except DatasetHasOpenTransactionError as e:
  # something else
except:
  # whatever
```
would be great.

### Alternatives you considered

An import of the errors like
```
from foundry_dev_tools import Errors

try:
   # something
except Errors.DatasetHasOpenTransactionError as e:
  # something else
except:
  # whatever
```
would be great.

### Additional Context

I

### PR DESCRIPTION
**Pull request by KochC**
# Summary

Initial PR for a new structure of exceptions.

# Checklist

- [x] You agree with our [CLA](https://gist.githubusercontent.com/emdgroup-admin/16cc45ea4315c2ef29eb9d9afc36fcf5/raw/abb9c91f15278a62b9ac3e66144bcd27fa9485c2/CLA.md)
- [ ] Included tests (or is not applicable).
- [ ] Updated [documentation](https://emdgroup.github.io/foundry-dev-tools/) (or is not applicable).
- [x] Used [pre-commit hooks](https://emdgroup.github.io/foundry-dev-tools/develop.html#pre-commit-hooks-formatting) to format and lint the code.
- [ ] Upgrade plan implemented / downwards compatibility implemented

### CODE REVIEW

**Comment by jonas-w** [comment]
Extensions? You mean exceptions?

**Comment by KochC** [comment]
> Extensions? You mean exceptions?

yes, sorry for the confusion 😉 Before merging I suggest to discuss if the new structure makes sense, and then continue with some more examples before a final merge.

**Comment by jonas-w** [comment]
> > Extensions? You mean exceptions?
> 
> yes, sorry for the confusion wink Before merging I suggest to discuss if the new structure makes sense, and then continue with some more examples before a final merge.

No problem ^^. Could you please fix the merge conflict, that the tests can run?

**Comment by jonas-w** [comment]
LGTM, but ffs should be renamed to something more descriptive.

**Comment by nicornk** [comment]
Thanks for the contribution @KochC . I need to review this properly - please keep it open for now.

**Comment by jonas-w** [comment]
We will also need deprecation warnings, otherwise it may instantly break code other people wrote.

**Comment by nilskch** [comment]
At the end before merging into the main branch, I suggest to squash the commits into one and reference the issue you raised in the commit message by adding "(#5)" at the end of the commit message.

**Pull request closed without merging**
